FROM alpine:3.18

RUN apk add --no-cache \
    python3 \
    py3-pip \
    openssh-client \
    bash && \
    pip3 install --no-cache-dir ansible==2.10.7

WORKDIR /ansible

CMD ["ansible-playbook", "--version"]

