FROM alpine:3.20

RUN apk add --no-cache \
    python3 \
    py3-pip \
    openssh-client \
    bash && \
    pip3 install --no-cache-dir ansible

WORKDIR /ansible

CMD ["ansible-playbook", "--version"]

