version: '3.7'

services:

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db-vol:/var/lib/mysql

volumes:
  db-vol:
